### PR TITLE
The Y waypoint properties now uses the WPILib Std bottom left +

### PR DESCRIPTION
**Pull request by jasondaming**

### CODE REVIEW

**Comment by carbotaniuman** [comment]
I don't see any files changed in this?

**Comment by jasondaming** [comment]
Weird.  Fixed now

**Comment by AustinShalit** [comment]
@jasondaming Please take a look at failing builds.

Also, this is safe to merge in the middle of a season?

**Comment by jasondaming** [comment]
See the larger discussion of changes.  IMO this is one of the least risky as it is just a UI change that I think will only be more intuitive for users coming from the WPILib coordinate way of doing things!

Fixed the build.

**Review by AustinShalit — APPROVED** [review]

**Pull request merged**
