### PR TITLE
Initial switch from Pathfinder to WPILib splines

### PR DESCRIPTION
**Pull request by carbotaniuman**
This code replaces Pathfinder splines used previously with
WPILib splines, as well as doing minor refactors of Path, Spline,
and Waypoint to clean up code quality and eventually allow for
multiple spline implementations.

### CODE REVIEW

**Comment by gftabor** [comment]
I see a lot of passing wpilib spline new. I'd suggest starting now with an abstraction layer if you want to eventually support multiple backends.

While you're replacing backend is the easiest time to implement it.

**Comment by gftabor** [comment]
Runs incredibly well. Code is looking good so far. My main concern left is, as we discussed, the strangeness in wpilib spline generation. They hardcode some magic constant magnitude on the control vector and only use the direction. While Pathweaver has the desired control vector and is unable to pass it.  

https://github.com/wpilibsuite/allwpilib/blob/457f94ba26ad944019b07a2868b91acbb8fbcb25/wpilibj/src/main/java/edu/wpi/first/wpilibj/spline/SplineHelper.java#L50

Once you test everything with modified version of that function, they should overload to support passing in control vectors.

**Comment by prateekma** [comment]
From the user side, supporting arbitrary control vectors would be incredibly verbose and honestly in my opinion, not needed. I anticipate most users using the clamped cubic splines, which only requires users to provide directions at endpoints. Thoughts? @Oblarg @calcmogul

**Comment by Oblarg** [comment]
I think we should expose overloads that allow full control vectors.  Teams don't have to use them, but the functionality ought to be there.

I also suggest log-scaling the control vector length in pathweaver - the visible control vector lengths can end up unfortunately long if you don't.

**Comment by gftabor** [comment]
Also it looks like dragging a waypoint resets the magnitude of vectors near it?

Something funky is going on, that I would  guess is you are redoing the sqrt on the magnitude when you shouldnt be.

**Comment by gftabor** [comment]
Closes 146 . WPI Traj Gen fixes
closes 145 . WPI Traj Gen fixes
closes 144 
closes 141 . WPI Traj Gen fixes
closes 63 . Pathfinder v2 no longer required

(affects #107  too but probably requires  method of loading new backends without building)

**Comment by gftabor** [comment]
Closes  #140 
Closes #74

**Pull request merged**
