### PR TITLE
Reversed splines

### LINKED ISSUE #176: Support reversed trajectories
Given a trajectory from point A to point B that a robot follows by driving forward, WPILib's trajectory generation library supports doing the time reversed version of that. To do that, set the reversed flag in TrajectoryConfig, then provide point B followed by point A to TrajectoryGenerator.

PathWeaver should support setting the reversed flag on a per-path level. It could be given a different color from forward paths.

### PR DESCRIPTION
**Pull request by CarlinWilliamson**
resolves #176 

Adds the ability to plot reverse splines (where the robot drives backwards)

These are indicated by a dashed line and can be toggled using the right click menu on the waypoints.

### CODE REVIEW

**Comment by CarlinWilliamson** [comment]
Things I don't like here:
 - My testing has only gone as far as observing the json files of the same path when reversed and not reversed
 - This involved adding a boolean property to every waypoint (avoiding significant changes to PathIOUtil.java) which is unintuative at best
 - The right click menu for toggling the direction is on the waypoints not the spline itself
 - Reversed is not included in the "waypoint properties" menu (it should really be in a path properties menu)

I should have access to a robot to test this in a few days.

My suggestion for fixing this boolean property issue would be to rework PathIOUtil to use json (so you can have properties for the path not the waypoints), move the right click menu to the spline and create a "path properties" menu.
Looks like a fair bit of work... Perhaps it should go in a seperate PR? Thoughts?

**Comment by Daltz333** [comment]
Your suggestions seem like a fair idea. Unfortunately, dev momentum on this project is pretty bare-bones. I would continue forward, and when it's ready for review, we can at least test the changes and see about merging then.

**Comment by CarlinWilliamson** [comment]
I did end up adding resverse splines to the "waypoint properties" menu.
Tested it tonight and I'm happy with things.

**Review by AustinShalit — CHANGES_REQUESTED** [review]
@CarlinWilliamson This looks really cool! One change to make before merging is if you could disable the checkbox when there is no path selected. Thank you@

**Review by AustinShalit — APPROVED** [review]

**Pull request merged**
