### PR TITLE
when a new path is clicked on the first waypoint is selected

### LINKED ISSUE #196: When Selecting a new Path the Waypoint properties of the previous waypoint don't clear
When multiple paths are created and saved and the user switches between them it will still show the Waypoint Properties of the a waypoint on the previous path.

**To Reproduce**  
1. Create Path 1
2. Create Path 2
3. Select a Waypoint on Path 2
4. Under Paths on the right choose path 1
5. Observe the Waypoint from path 2 is still showing in the Waypoint Properties box

**Expected behavior**  
It should either clear the Waypoint properties or select the first waypoint.

**Desktop:**
 - OS: Windows
 - Java version
C:\Users\jason>java -version
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)

### LINKED ISSUE #214: Clicking on a path should highlight the first waypoint in waypoint properties
Currently nothing is changed.  Even worse is that the data in waypoint properties could even be from an old waypoint from a different path.

### PR DESCRIPTION
**Pull request by jasondaming**
Closes #214 
Closes #196

### CODE REVIEW

**Comment by carbotaniuman** [comment]
LGTM

**Comment by AustinShalit** [comment]
@jasondaming Can you look at ways we can make it so quickly switching between paths without making edits will not cause the "do you want to save" dialog to show up?

**Comment by jasondaming** [comment]
okay would that be in this PR or separate?

**Comment by AustinShalit** [comment]
I think in this PR because I do not see the behavior on the main branch.

**Comment by jasondaming** [comment]
Normally when you click on a path it doesn't actually activate any of the waypoints.  To recreate click on a path then on a waypoint in that path then click on different path.

The problem here is that any time a path is "selected" it is added to the list of paths to be checked for modifications.

**Review by AustinShalit — APPROVED** [review]

**Pull request merged**
